In [5]:
#Creating Arrays from Tuple
num1=(10,20,30,40,50)
my_arrays=np.array((num1))
my_arrays

array([10, 20, 30, 40, 50])

In [2]:
#Creating Arrays from list
import numpy as np
mylist1=[1,2,3,4]
mylist2=[5,6,7,8]
my_array=np.array(mylist1)
my_array

array([1, 2, 3, 4])

In [3]:
my_array2=np.array([mylist1,mylist2])
my_array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
#We can convert the elements to floats
my_array3=np.array([mylist1,mylist2],dtype='float')
my_array3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [9]:
#Basic array characteristics
#Type of array object
print(type(my_array))
print(type(my_array2))
print(type(my_arrays))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
#Array Dimension
print(my_array.ndim)
print(my_array2.ndim)
print(my_arrays.ndim)

1
2
1


In [11]:
#Shape of array
print(my_array.shape)
print(my_array2.shape)
print(my_arrays.shape)

(4,)
(2, 4)
(5,)


In [12]:
#Total number of elements
print(my_array.size)
print(my_array2.size)
print(my_arrays.size)

4
8
5


In [20]:
#Type of elements in array
print(my_array.dtype)
print(my_array3.dtype)

int64
float64


In [15]:
#Other methods of creating arrays
#Zeros function
arr1=np.zeros(5) #This create an array of 5 zeros in one dimension
print(arr1) #This is also same as the empty function

[0. 0. 0. 0. 0.]


In [23]:
arr2=np.zeros((3,5)) #This creates arrays of zeros with 3 rows and 5 columns
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
#Ones Fucntion
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [25]:
arr4=np.ones((4,5))
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
#arange function
arr5=np.arange(2,20,3) #This gives sequence of integers between 2 and 20 with a step of 3
arr5

array([ 2,  5,  8, 11, 14, 17])

In [27]:
arr6=np.arange(0,30,5)
arr6

array([ 0,  5, 10, 15, 20, 25])

In [28]:
#linspace function
arr7= np.linspace(0, 5, 10) #This gives a sequence of 10 values between the range of 0 and 5
arr7

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
#eye function
arr8=np.eye(3) #This gives an identity matrix
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#random numbers
#random.rand
#This populates random values from a uniform distribution, over 0 to 1
arr9 = np.random.random((3, 4)) #This gives random values with 3 rows and 4 columns
arr9

array([[0.32189421, 0.14256091, 0.48044565, 0.54466155],
       [0.00965977, 0.86135047, 0.06209333, 0.46109624],
       [0.55633341, 0.59177062, 0.97962407, 0.49826332]])

In [44]:
#random.randn
#This return numbers from standard normal distribution centered around 0
arr10=np.random.randn(3)
arr10

array([ 0.12445039, -0.10300406, -1.04440913])

In [6]:
print(np.random.randn(2,3))

[[ 1.66354761 -0.04536298  1.2117675 ]
 [ 0.14969344  0.60896466 -0.56758432]]


In [53]:
#random.randint
#This returns integers from a range of values where the higher value isnt included.
#The third argument specifies the count of random integers to be generated.
np.random.randint(3,100,20)


array([55, 18, 25, 79, 95, 74, 93, 36, 97, 46, 96, 87, 49,  5,  7, 96, 45,
       45, 84, 96])

In [54]:
np.random.randint(0,50,10)


array([39, 22, 24, 24,  5, 22, 38, 11, 43, 32])

In [32]:
#reshape function
my_array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
my_array2.shape

(2, 4)

In [39]:
my_array2.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
my_array2.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
arr_1 = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 
  
newarr = arr_1.reshape(2, 2, 3)
print("Initial Array is:", arr_1)
print("Reshaped Array is:",newarr)

Initial Array is: [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped Array is: [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [37]:
#Flatttening Arrays
my_array2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
#Indexing and slicing arrays (1D)
arr5

array([ 2,  5,  8, 11, 14, 17])

In [56]:
arr5[3]

11

In [58]:
arr5[2:]

array([ 8, 11, 14, 17])

In [59]:
arr5[2:5]

array([ 8, 11, 14])

In [66]:
#Replacement by broadcasting
my_arr2=np.arange(5,20)
my_arr2[0:5]

array([5, 6, 7, 8, 9])

In [67]:
my_arr2[0:3]=0
my_arr2

array([ 0,  0,  0,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [65]:
#Replacement by broadcasting
arr5[2:4]=25
arr5

array([ 2,  5, 25, 25, 14, 17])

In [69]:
#Copying  elements from one variable into another
arr_cp=my_arr2.copy()
arr_cp

array([ 0,  0,  0,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [71]:
arr_cp[:]=10
arr_cp

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [3]:
#Indexing and Slicing (2D)
my_arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
my_arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
#The Double square bracket method
print(my_arr3[0][2])
print(my_arr3[2][2])
print(my_arr3[1][0])

3
9
4


In [77]:
#The Single sqaure bracket method
print(my_arr3[0,2])
print(my_arr3[1,0])

3
4


In [80]:
#Extracting Sections
print(my_arr3[0:2,0:2])
print(my_arr3[1:2,0:2])

[[1 2]
 [4 5]]
[[4 5]]


In [60]:
my_arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]])
my_arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [63]:
my_arr[:2,::2] #The two columns means count from the back

array([[-1.,  0.],
       [ 4.,  6.]])

In [64]:
my_arr[:2,:3]

array([[-1. ,  2. ,  0. ],
       [ 4. , -0.5,  6. ]])

In [8]:
#Unique Values
number_list=np.array([11,11,11,12,13,14,15,14,12,11,16,17,18,19,18])
np.unique(number_list)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
#Showing the index of elements
np.unique(number_list,return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([ 0,  3,  4,  5,  6, 10, 11, 12, 13]))

In [10]:
#We can also get the counts of each item
np.unique(number_list,return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([4, 2, 1, 2, 1, 1, 1, 2, 1]))

In [13]:
#Getting unique values from a 2D array
arr2d=np.array([[11,11,12,11],[13,11,12,11],[16,11,12,11],[11,11,12,11]])
print(arr2d)
print(np.unique(arr2d)) #result is flattened as axis argument is not passed

[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
[11 12 13 16]


In [14]:
#Getting Unique values from rows
np.unique(arr2d,axis=0)

array([[11, 11, 12, 11],
       [13, 11, 12, 11],
       [16, 11, 12, 11]])

In [15]:
#Getting Unique values from columns
np.unique(arr2d, axis=1)

array([[11, 11, 12],
       [11, 13, 12],
       [11, 16, 12],
       [11, 11, 12]])

In [16]:
#We can get unique values and Occurence count
np.unique(arr2d,axis=1,return_counts=True)

(array([[11, 11, 12],
        [11, 13, 12],
        [11, 16, 12],
        [11, 11, 12]]),
 array([2, 1, 1]))

In [18]:
np.unique(arr2d,axis=0,return_counts=True)

(array([[11, 11, 12, 11],
        [13, 11, 12, 11],
        [16, 11, 12, 11]]),
 array([2, 1, 1]))

In [82]:
#Conditional Selection
cond=my_arr>2
temp=my_arr[cond]
temp

array([4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. ])

In [83]:
my_arr2

array([ 0,  0,  0,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [86]:
print(my_arr2[my_arr2>10])
print(my_arr2[my_arr2<14])

[11 12 13 14 15 16 17 18 19]
[ 0  0  0  8  9 10 11 12 13]


In [99]:
#Basic Numpy Operations
a=np.array([1,2,5,3])
a

array([1, 2, 5, 3])

In [89]:
#Adding 5 to every element
a+5

array([ 6,  7, 10,  8])

In [91]:
#subtract 3 from every item
a-3

array([-2, -1,  2,  0])

In [92]:
#multiply each item by 10
a*10

array([10, 20, 50, 30])

In [93]:
#square each element
a**2

array([ 1,  4, 25,  9])

In [102]:
#double each element
a*=2
a

array([ 4,  8, 20, 12])

In [103]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
#Transposing arrays
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [106]:
#Unary Opeartions on arrays
my_arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
#Maximum element of array
my_arr3.max()

9

In [108]:
#Column-wise max
my_arr3.max(axis=0)

array([7, 8, 9])

In [109]:
#Row-wise max
my_arr3.max(axis=1)

array([3, 6, 9])

In [4]:
#Note that we can also know the index of the max and min values with the argmax & argmin function.
my_arr3.argmax()

8

In [5]:
my_arr3.argmin()

0

In [111]:
#Sum of all elements in array
my_arr3.sum()

45

In [112]:
#Cummulative Sum along each row
my_arr3.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [113]:
#Binary Operations on arrays
#add arrays
arr8+my_arr3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [114]:
#Elementwise multiplication
arr8*my_arr3

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [115]:
#Matrix multiplication(dot product)
arr8.dot(my_arr3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [138]:
#Note: all the mathematical operations performed above can be done using the following universal function;
#i.e np.add,np.subtract,np.multiply,np.divide,np.sum etc

In [139]:
#Other important universal functions are;
#Sine functions
pi_values=[0,np.pi/2,np.pi]
np.sin(pi_values)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [140]:
#Cos function
np.cos(pi_values)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [142]:
#Squareroot
values2=[4,9,16,36]
np.sqrt(values2)

array([2., 3., 4., 6.])

In [143]:
#Exp function
np.exp(values2)
#We also have the log function

array([5.45981500e+01, 8.10308393e+03, 8.88611052e+06, 4.31123155e+15])

In [144]:
#Sorting Arrays
a_val=([1,4,2],[3,4,6],[-1,0,5])
np.sort(a_val,axis=None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

In [145]:
#Row-wise Sorting
np.sort(a_val,axis=1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [146]:
#Column-wise Sorting
np.sort(a_val,axis=0)

array([[-1,  0,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [149]:
#Sorting of Structured Arrays
val_data=[('Hleb',2009,8.5),('Ajayi',2008,8.7),('Patrick',2008,7.9),('Aleisha',2009,9.0)]
data_types=[('name','S10'),('grad_year',int),('cgpa',float)]
info_array=np.array(val_data,dtype=data_types)
info_array


array([(b'Hleb', 2009, 8.5), (b'Ajayi', 2008, 8.7),
       (b'Patrick', 2008, 7.9), (b'Aleisha', 2009, 9. )],
      dtype=[('name', 'S10'), ('grad_year', '<i8'), ('cgpa', '<f8')])

In [152]:
np.sort(info_array,order='name')

array([(b'Ajayi', 2008, 8.7), (b'Aleisha', 2009, 9. ),
       (b'Hleb', 2009, 8.5), (b'Patrick', 2008, 7.9)],
      dtype=[('name', 'S10'), ('grad_year', '<i8'), ('cgpa', '<f8')])

In [153]:
np.sort(info_array,order=['grad_year','cgpa'])

array([(b'Patrick', 2008, 7.9), (b'Ajayi', 2008, 8.7),
       (b'Hleb', 2009, 8.5), (b'Aleisha', 2009, 9. )],
      dtype=[('name', 'S10'), ('grad_year', '<i8'), ('cgpa', '<f8')])