In [2]:
import numpy as np
#Stacking Arrays
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#Vertical Stacking
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [3]:
#Horizontal Stacking
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [4]:
#Colums Stacking
c=[11,12]
np.column_stack((a,c))

array([[ 1,  2, 11],
       [ 3,  4, 12]])

In [5]:
#We can use the Conatenation method to achieve Stacking
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
np.concatenate((a,b),1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
dataset1=np.arange(25).reshape(5,5)
dataset2=np.random.randn(25).reshape(5,5)
print(dataset1)
print(dataset2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1.07142899  0.98446791  0.66377718 -0.30753737  2.3279408 ]
 [-1.10219646  0.94421933  1.61667454  1.43227678 -0.65450018]
 [-0.31886697  0.95437629 -0.27245879 -0.60457949  0.24295735]
 [-0.75352707 -1.04222591  0.12385893 -1.54533976  0.42038241]
 [-0.65617497 -0.61190056 -1.08984794 -1.52643495 -1.36981407]]


In [22]:
print(np.concatenate([dataset1,dataset2],axis=1)) #This concatenates along columns
print(np.concatenate([dataset1,dataset2],axis=0)) #This concatenates along rows

[[ 0.          1.          2.          3.          4.          1.07142899
   0.98446791  0.66377718 -0.30753737  2.3279408 ]
 [ 5.          6.          7.          8.          9.         -1.10219646
   0.94421933  1.61667454  1.43227678 -0.65450018]
 [10.         11.         12.         13.         14.         -0.31886697
   0.95437629 -0.27245879 -0.60457949  0.24295735]
 [15.         16.         17.         18.         19.         -0.75352707
  -1.04222591  0.12385893 -1.54533976  0.42038241]
 [20.         21.         22.         23.         24.         -0.65617497
  -0.61190056 -1.08984794 -1.52643495 -1.36981407]]
[[ 0.          1.          2.          3.          4.        ]
 [ 5.          6.          7.          8.          9.        ]
 [10.         11.         12.         13.         14.        ]
 [15.         16.         17.         18.         19.        ]
 [20.         21.         22.         23.         24.        ]
 [ 1.07142899  0.98446791  0.66377718 -0.30753737  2.327940

In [8]:
#Splitting Arrays
d=np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])
#Horozontal Split
np.hsplit(d,3)

[array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]),
 array([[ 9, 11],
        [10, 12]])]

In [10]:
#Vertical Split
np.vsplit(d,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [3]:
#Working with Datetime
today=np.datetime64('2017-02-12')
today

numpy.datetime64('2017-02-12')

In [4]:
np.datetime64(today,'Y')

numpy.datetime64('2017')

In [8]:
#Creating Arrays of dates in a month
dates=np.arange('2017-02','2017-03',dtype='datetime64[D]')
dates

array(['2017-02-01', '2017-02-02', '2017-02-03', '2017-02-04',
       '2017-02-05', '2017-02-06', '2017-02-07', '2017-02-08',
       '2017-02-09', '2017-02-10', '2017-02-11', '2017-02-12',
       '2017-02-13', '2017-02-14', '2017-02-15', '2017-02-16',
       '2017-02-17', '2017-02-18', '2017-02-19', '2017-02-20',
       '2017-02-21', '2017-02-22', '2017-02-23', '2017-02-24',
       '2017-02-25', '2017-02-26', '2017-02-27', '2017-02-28'],
      dtype='datetime64[D]')

In [9]:
print(today in dates)

True


In [11]:
#Arithmetic Operations on Dates
arith_date=np.datetime64('2017-05-22')-np.datetime64('2016-05-22')
print(arith_date)
print(np.timedelta64(arith_date,'W'))

365 days
52 weeks


In [12]:
#Sorting Dates
dates1=np.array(['2017-02-12','2016-10-13','2019-05-22'],dtype='datetime64')
np.sort(dates1)

array(['2016-10-13', '2017-02-12', '2019-05-22'], dtype='datetime64[D]')

In [13]:
#NumPy Linear Algebra
matrix=np.array([[6,1,1],[4,-2,5],[2,8,7]])
matrix

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [14]:
#Rank of Matrix
np.linalg.matrix_rank(matrix)

3

In [15]:
#Determinant
np.linalg.det(matrix)

-306.0

In [16]:
#Inverse of Matrix
np.linalg.inv(matrix)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [17]:
#Power
np.linalg.matrix_power(matrix,3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [3]:
#Saving and Loading Arrays
#Saving single arrays
my_arrays1=np.arange(12)
my_arrays1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.save('saved_array1',my_arrays1) #This will save my_arrays1 as saved_arrays1 in npy format

In [5]:
#Loading the saved array
new_array=np.load('saved_array1.npy')
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
#Saving multiple arrays in Zip file
my_arrays2=np.arange(10)
my_arrays3=np.arange(20)
print(my_arrays2)
print(my_arrays3)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
np.savez('saved_archive.npz',x=my_arrays2,y=my_arrays3) #This will save it in zip format as saved_archive

In [10]:
my_archive=np.load('saved_archive.npz') #This will load the saved zip file

In [11]:
#Accesssing the saved archive
print(my_archive['x'])
print(my_archive['y'])

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [13]:
#Saving to a Textfile
np.savetxt('notepadfile.txt',my_arrays2,delimiter=',') #This creates a textfile folder

In [14]:
#Loading and Accessing the save text file
new_textfile=np.loadtxt('notepadfile.txt',delimiter=',')
new_textfile

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])